
import java.sql.*;

public class LoginJFrame extends javax.swing.JFrame {

    Statement st;
    String url = "jdbc:mysql://localhost:3306/stdinfo";
    String user = "root";
    String password = "root";
    Connection connection = null;
    String query = "select * from std_details;";
    ResultSet result;

    void getconnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the database!");
            if (connection != null) {
                st = connection.createStatement();
                result = st.executeQuery(query);
                if (result.first()) {
                    System.out.println("Roll : " + result.getInt("roll") + " Name : " + result.getString("name") + " DOB : " + result.getString("dob"));
                    rolltf.setText(String.valueOf(result.getInt("roll")));
                    nametf.setText(result.getString("name"));
                    dobtf.setText(result.getString("dob"));
                }
            }
        } catch (Exception e) {
            System.out.println("Connection failed ! " + e);
        }
    }

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        getconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        rolltf = new javax.swing.JTextField();
        dobtf = new javax.swing.JTextField();
        rollLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        firstbtn = new javax.swing.JButton();
        nextbtn = new javax.swing.JButton();
        prvsbtn = new javax.swing.JButton();
        lastbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setText("Name           :");

        nametf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        rolltf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        dobtf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        rollLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rollLabel.setText("Roll               :");

        dobLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dobLabel.setText("DOB             :");

        firstbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstbtn.setText("|<");
        firstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstbtnActionPerformed(evt);
            }
        });

        nextbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextbtn.setText(">");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });

        prvsbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prvsbtn.setText("<");
        prvsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prvsbtnActionPerformed(evt);
            }
        });

        lastbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastbtn.setText(">|");
        lastbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rollLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dobtf, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(rolltf)
                            .addComponent(nametf)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstbtn)
                        .addGap(68, 68, 68)
                        .addComponent(prvsbtn)
                        .addGap(60, 60, 60)
                        .addComponent(nextbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(lastbtn)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolltf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobtf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prvsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstbtnActionPerformed
        // TODO add your handling code here
        try {
            if (result.first()) {
                System.out.println("Roll : " + result.getInt("roll") + " Name : " + result.getString("name") + " DOB : " + result.getString("dob"));
                rolltf.setText(String.valueOf(result.getInt("roll")));
                nametf.setText(result.getString("name"));
                dobtf.setText(result.getString("dob"));
            }
        } catch (Exception e) {
            System.out.println("Some error Occured ! " + e);
        }
    }//GEN-LAST:event_firstbtnActionPerformed

    private void prvsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prvsbtnActionPerformed
        // TODO add your handling code here
        try {
            if (result.previous()) {
                System.out.println("Roll : " + result.getInt("roll") + " Name : " + result.getString("name") + " DOB : " + result.getString("dob"));
                rolltf.setText(String.valueOf(result.getInt("roll")));
                nametf.setText(result.getString("name"));
                dobtf.setText(result.getString("dob"));
            } 
        } catch (Exception e) {
            System.out.println("Some error Occured! " + e);
        }
    }//GEN-LAST:event_prvsbtnActionPerformed

    private void lastbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastbtnActionPerformed
        // TODO add your handling code here:
        try {

            if (result.last()) {
                System.out.println("Roll : " + result.getInt("roll") + " Name : " + result.getString("name") + " DOB : " + result.getString("dob"));
                rolltf.setText(String.valueOf(result.getInt("roll")));
                nametf.setText(result.getString("name"));
                dobtf.setText(result.getString("dob"));
            }
        } catch (Exception e) {
            System.out.println("Some error Occured! " + e);
        }
    }//GEN-LAST:event_lastbtnActionPerformed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        // TODO add your handling code here:
        try {
            if (result.next()) {
                System.out.println("Roll : " + result.getInt("roll") + " Name : " + result.getString("name") + " DOB : " + result.getString("dob"));
                rolltf.setText(String.valueOf(result.getInt("roll")));
                nametf.setText(result.getString("name"));
                dobtf.setText(result.getString("dob"));
            } 
        } catch (Exception e) {
            System.out.println("Somme error Occured! " + e);

        }
    }//GEN-LAST:event_nextbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobtf;
    private javax.swing.JButton firstbtn;
    private javax.swing.JButton lastbtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nametf;
    private javax.swing.JButton nextbtn;
    private javax.swing.JButton prvsbtn;
    private javax.swing.JLabel rollLabel;
    private javax.swing.JTextField rolltf;
    // End of variables declaration//GEN-END:variables
}
